# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 16.0
org_name: Coop IT Easy SC
org_slug: coopiteasy
rebel_module_groups: []
repo_description: hr_timesheet modules
repo_name: cie-timesheet
repo_slug: cie-timesheet
repo_website: https://github.com/coopiteasy/cie-timesheet
use_pyproject_toml: false
use_ruff: false

